/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { EventFragment, FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  OnEvent,
  PromiseOrValue,
  TypedEvent,
  TypedEventFilter,
  TypedListener,
} from "../../common";

export interface HermesTestInterface extends utils.Interface {
  functions: {
    "addListing(uint256,uint256,uint48)": FunctionFragment;
    "agreed(address)": FunctionFragment;
    "borrow(uint256)": FunctionFragment;
    "calculateCollateral(uint256,uint256)": FunctionFragment;
    "calculateInterest(uint256,uint256)": FunctionFragment;
    "claim(uint256)": FunctionFragment;
    "drachma()": FunctionFragment;
    "echidnaBalanceExceedsLendersInterest()": FunctionFragment;
    "echidnaBorrowerClaimedClosesTheLoan()": FunctionFragment;
    "echidnaCollateralIsGreaterThanInterest()": FunctionFragment;
    "echidnaDrachmaIsConstant()": FunctionFragment;
    "echidnaDurationIsNonNegative()": FunctionFragment;
    "echidnaIfAgreedMustBeInvoledWithALoan()": FunctionFragment;
    "echidnaLenderAndBorrowerCannotBeTheSame()": FunctionFragment;
    "echidnaListingDurationIsNonNegative()": FunctionFragment;
    "echidnaListingPriceIsNonNegative()": FunctionFragment;
    "echidnaOlympusIsConstant()": FunctionFragment;
    "echidnaPriceIsNonNegative()": FunctionFragment;
    "echidnaStartTimeIsNonNegative()": FunctionFragment;
    "emergencyWithdraw(uint256)": FunctionFragment;
    "liquidate(uint256)": FunctionFragment;
    "listings(uint256)": FunctionFragment;
    "loans(uint256)": FunctionFragment;
    "olympus()": FunctionFragment;
    "onERC721Received(address,address,uint256,bytes)": FunctionFragment;
    "owner()": FunctionFragment;
    "pause()": FunctionFragment;
    "paused()": FunctionFragment;
    "payoff(uint256)": FunctionFragment;
    "removeListing(uint256)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "topup(uint256,uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "unpause()": FunctionFragment;
    "updatePrices(uint256[],uint256[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addListing"
      | "agreed"
      | "borrow"
      | "calculateCollateral"
      | "calculateInterest"
      | "claim"
      | "drachma"
      | "echidnaBalanceExceedsLendersInterest"
      | "echidnaBorrowerClaimedClosesTheLoan"
      | "echidnaCollateralIsGreaterThanInterest"
      | "echidnaDrachmaIsConstant"
      | "echidnaDurationIsNonNegative"
      | "echidnaIfAgreedMustBeInvoledWithALoan"
      | "echidnaLenderAndBorrowerCannotBeTheSame"
      | "echidnaListingDurationIsNonNegative"
      | "echidnaListingPriceIsNonNegative"
      | "echidnaOlympusIsConstant"
      | "echidnaPriceIsNonNegative"
      | "echidnaStartTimeIsNonNegative"
      | "emergencyWithdraw"
      | "liquidate"
      | "listings"
      | "loans"
      | "olympus"
      | "onERC721Received"
      | "owner"
      | "pause"
      | "paused"
      | "payoff"
      | "removeListing"
      | "renounceOwnership"
      | "topup"
      | "transferOwnership"
      | "unpause"
      | "updatePrices"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addListing",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "agreed", values: [PromiseOrValue<string>]): string;
  encodeFunctionData(functionFragment: "borrow", values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(
    functionFragment: "calculateCollateral",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateInterest",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "claim", values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(functionFragment: "drachma", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "echidnaBalanceExceedsLendersInterest",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "echidnaBorrowerClaimedClosesTheLoan",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "echidnaCollateralIsGreaterThanInterest",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "echidnaDrachmaIsConstant", values?: undefined): string;
  encodeFunctionData(functionFragment: "echidnaDurationIsNonNegative", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "echidnaIfAgreedMustBeInvoledWithALoan",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "echidnaLenderAndBorrowerCannotBeTheSame",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "echidnaListingDurationIsNonNegative",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "echidnaListingPriceIsNonNegative",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "echidnaOlympusIsConstant", values?: undefined): string;
  encodeFunctionData(functionFragment: "echidnaPriceIsNonNegative", values?: undefined): string;
  encodeFunctionData(functionFragment: "echidnaStartTimeIsNonNegative", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "liquidate", values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(functionFragment: "listings", values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(functionFragment: "loans", values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(functionFragment: "olympus", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(functionFragment: "payoff", values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(
    functionFragment: "removeListing",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "renounceOwnership", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "topup",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updatePrices",
    values: [PromiseOrValue<BigNumberish>[], PromiseOrValue<BigNumberish>[]]
  ): string;

  decodeFunctionResult(functionFragment: "addListing", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "agreed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "borrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "calculateCollateral", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "calculateInterest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "drachma", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "echidnaBalanceExceedsLendersInterest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "echidnaBorrowerClaimedClosesTheLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "echidnaCollateralIsGreaterThanInterest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "echidnaDrachmaIsConstant", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "echidnaDurationIsNonNegative", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "echidnaIfAgreedMustBeInvoledWithALoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "echidnaLenderAndBorrowerCannotBeTheSame",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "echidnaListingDurationIsNonNegative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "echidnaListingPriceIsNonNegative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "echidnaOlympusIsConstant", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "echidnaPriceIsNonNegative", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "echidnaStartTimeIsNonNegative", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "emergencyWithdraw", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "liquidate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "listings", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "loans", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "olympus", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "onERC721Received", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payoff", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "removeListing", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "renounceOwnership", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "topup", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transferOwnership", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "updatePrices", data: BytesLike): Result;

  events: {
    "AddListing(address,uint256,uint256,uint256)": EventFragment;
    "Borrow(address,uint256)": EventFragment;
    "Liquidate(uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Paused(address)": EventFragment;
    "RemoveListing(uint256)": EventFragment;
    "RemoveLoan(uint256)": EventFragment;
    "Unpaused(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AddListing"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Borrow"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Liquidate"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RemoveListing"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RemoveLoan"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
}

export interface AddListingEventObject {
  lender: string;
  tokenId: BigNumber;
  price: BigNumber;
  duration: BigNumber;
}
export type AddListingEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber],
  AddListingEventObject
>;

export type AddListingEventFilter = TypedEventFilter<AddListingEvent>;

export interface BorrowEventObject {
  borrower: string;
  tokenId: BigNumber;
}
export type BorrowEvent = TypedEvent<[string, BigNumber], BorrowEventObject>;

export type BorrowEventFilter = TypedEventFilter<BorrowEvent>;

export interface LiquidateEventObject {
  tokenId: BigNumber;
}
export type LiquidateEvent = TypedEvent<[BigNumber], LiquidateEventObject>;

export type LiquidateEventFilter = TypedEventFilter<LiquidateEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter = TypedEventFilter<OwnershipTransferredEvent>;

export interface PausedEventObject {
  account: string;
}
export type PausedEvent = TypedEvent<[string], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface RemoveListingEventObject {
  tokenId: BigNumber;
}
export type RemoveListingEvent = TypedEvent<[BigNumber], RemoveListingEventObject>;

export type RemoveListingEventFilter = TypedEventFilter<RemoveListingEvent>;

export interface RemoveLoanEventObject {
  tokenId: BigNumber;
}
export type RemoveLoanEvent = TypedEvent<[BigNumber], RemoveLoanEventObject>;

export type RemoveLoanEventFilter = TypedEventFilter<RemoveLoanEvent>;

export interface UnpausedEventObject {
  account: string;
}
export type UnpausedEvent = TypedEvent<[string], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface HermesTest extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: HermesTestInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addListing(
      tokenId: PromiseOrValue<BigNumberish>,
      price: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    agreed(arg0: PromiseOrValue<string>, overrides?: CallOverrides): Promise<[boolean]>;

    borrow(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    calculateCollateral(
      price: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    calculateInterest(
      price: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    claim(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    drachma(overrides?: CallOverrides): Promise<[string]>;

    echidnaBalanceExceedsLendersInterest(overrides?: CallOverrides): Promise<[boolean]>;

    echidnaBorrowerClaimedClosesTheLoan(overrides?: CallOverrides): Promise<[boolean]>;

    echidnaCollateralIsGreaterThanInterest(overrides?: CallOverrides): Promise<[boolean]>;

    echidnaDrachmaIsConstant(overrides?: CallOverrides): Promise<[boolean]>;

    echidnaDurationIsNonNegative(overrides?: CallOverrides): Promise<[boolean]>;

    echidnaIfAgreedMustBeInvoledWithALoan(overrides?: CallOverrides): Promise<[boolean]>;

    echidnaLenderAndBorrowerCannotBeTheSame(overrides?: CallOverrides): Promise<[boolean]>;

    echidnaListingDurationIsNonNegative(overrides?: CallOverrides): Promise<[boolean]>;

    echidnaListingPriceIsNonNegative(overrides?: CallOverrides): Promise<[boolean]>;

    echidnaOlympusIsConstant(overrides?: CallOverrides): Promise<[boolean]>;

    echidnaPriceIsNonNegative(overrides?: CallOverrides): Promise<[boolean]>;

    echidnaStartTimeIsNonNegative(overrides?: CallOverrides): Promise<[boolean]>;

    emergencyWithdraw(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    liquidate(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    listings(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, number, BigNumber] & {
        lender: string;
        duration: number;
        price: BigNumber;
      }
    >;

    loans(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, boolean, string, number, number, BigNumber] & {
        price: BigNumber;
        lender: string;
        borrowerClaimed: boolean;
        borrower: string;
        startTime: number;
        duration: number;
        collateral: BigNumber;
      }
    >;

    olympus(overrides?: CallOverrides): Promise<[string]>;

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pause(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    payoff(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeListing(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    topup(
      tokenId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updatePrices(
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _prices: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  addListing(
    tokenId: PromiseOrValue<BigNumberish>,
    price: PromiseOrValue<BigNumberish>,
    duration: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  agreed(arg0: PromiseOrValue<string>, overrides?: CallOverrides): Promise<boolean>;

  borrow(
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  calculateCollateral(
    price: PromiseOrValue<BigNumberish>,
    duration: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  calculateInterest(
    price: PromiseOrValue<BigNumberish>,
    duration: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  claim(
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  drachma(overrides?: CallOverrides): Promise<string>;

  echidnaBalanceExceedsLendersInterest(overrides?: CallOverrides): Promise<boolean>;

  echidnaBorrowerClaimedClosesTheLoan(overrides?: CallOverrides): Promise<boolean>;

  echidnaCollateralIsGreaterThanInterest(overrides?: CallOverrides): Promise<boolean>;

  echidnaDrachmaIsConstant(overrides?: CallOverrides): Promise<boolean>;

  echidnaDurationIsNonNegative(overrides?: CallOverrides): Promise<boolean>;

  echidnaIfAgreedMustBeInvoledWithALoan(overrides?: CallOverrides): Promise<boolean>;

  echidnaLenderAndBorrowerCannotBeTheSame(overrides?: CallOverrides): Promise<boolean>;

  echidnaListingDurationIsNonNegative(overrides?: CallOverrides): Promise<boolean>;

  echidnaListingPriceIsNonNegative(overrides?: CallOverrides): Promise<boolean>;

  echidnaOlympusIsConstant(overrides?: CallOverrides): Promise<boolean>;

  echidnaPriceIsNonNegative(overrides?: CallOverrides): Promise<boolean>;

  echidnaStartTimeIsNonNegative(overrides?: CallOverrides): Promise<boolean>;

  emergencyWithdraw(
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  liquidate(
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  listings(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [string, number, BigNumber] & {
      lender: string;
      duration: number;
      price: BigNumber;
    }
  >;

  loans(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, boolean, string, number, number, BigNumber] & {
      price: BigNumber;
      lender: string;
      borrowerClaimed: boolean;
      borrower: string;
      startTime: number;
      duration: number;
      collateral: BigNumber;
    }
  >;

  olympus(overrides?: CallOverrides): Promise<string>;

  onERC721Received(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    arg2: PromiseOrValue<BigNumberish>,
    arg3: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  pause(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  payoff(
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeListing(
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  topup(
    tokenId: PromiseOrValue<BigNumberish>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unpause(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<ContractTransaction>;

  updatePrices(
    _tokenIds: PromiseOrValue<BigNumberish>[],
    _prices: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addListing(
      tokenId: PromiseOrValue<BigNumberish>,
      price: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    agreed(arg0: PromiseOrValue<string>, overrides?: CallOverrides): Promise<boolean>;

    borrow(tokenId: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<void>;

    calculateCollateral(
      price: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateInterest(
      price: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claim(tokenId: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<void>;

    drachma(overrides?: CallOverrides): Promise<string>;

    echidnaBalanceExceedsLendersInterest(overrides?: CallOverrides): Promise<boolean>;

    echidnaBorrowerClaimedClosesTheLoan(overrides?: CallOverrides): Promise<boolean>;

    echidnaCollateralIsGreaterThanInterest(overrides?: CallOverrides): Promise<boolean>;

    echidnaDrachmaIsConstant(overrides?: CallOverrides): Promise<boolean>;

    echidnaDurationIsNonNegative(overrides?: CallOverrides): Promise<boolean>;

    echidnaIfAgreedMustBeInvoledWithALoan(overrides?: CallOverrides): Promise<boolean>;

    echidnaLenderAndBorrowerCannotBeTheSame(overrides?: CallOverrides): Promise<boolean>;

    echidnaListingDurationIsNonNegative(overrides?: CallOverrides): Promise<boolean>;

    echidnaListingPriceIsNonNegative(overrides?: CallOverrides): Promise<boolean>;

    echidnaOlympusIsConstant(overrides?: CallOverrides): Promise<boolean>;

    echidnaPriceIsNonNegative(overrides?: CallOverrides): Promise<boolean>;

    echidnaStartTimeIsNonNegative(overrides?: CallOverrides): Promise<boolean>;

    emergencyWithdraw(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    liquidate(tokenId: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<void>;

    listings(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, number, BigNumber] & {
        lender: string;
        duration: number;
        price: BigNumber;
      }
    >;

    loans(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, boolean, string, number, number, BigNumber] & {
        price: BigNumber;
        lender: string;
        borrowerClaimed: boolean;
        borrower: string;
        startTime: number;
        duration: number;
        collateral: BigNumber;
      }
    >;

    olympus(overrides?: CallOverrides): Promise<string>;

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    pause(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    payoff(tokenId: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<void>;

    removeListing(tokenId: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    topup(
      tokenId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(newOwner: PromiseOrValue<string>, overrides?: CallOverrides): Promise<void>;

    unpause(overrides?: CallOverrides): Promise<void>;

    updatePrices(
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _prices: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AddListing(address,uint256,uint256,uint256)"(
      lender?: null,
      tokenId?: null,
      price?: null,
      duration?: null
    ): AddListingEventFilter;
    AddListing(lender?: null, tokenId?: null, price?: null, duration?: null): AddListingEventFilter;

    "Borrow(address,uint256)"(borrower?: null, tokenId?: null): BorrowEventFilter;
    Borrow(borrower?: null, tokenId?: null): BorrowEventFilter;

    "Liquidate(uint256)"(tokenId?: null): LiquidateEventFilter;
    Liquidate(tokenId?: null): LiquidateEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "RemoveListing(uint256)"(tokenId?: null): RemoveListingEventFilter;
    RemoveListing(tokenId?: null): RemoveListingEventFilter;

    "RemoveLoan(uint256)"(tokenId?: null): RemoveLoanEventFilter;
    RemoveLoan(tokenId?: null): RemoveLoanEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;
  };

  estimateGas: {
    addListing(
      tokenId: PromiseOrValue<BigNumberish>,
      price: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    agreed(arg0: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>;

    borrow(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    calculateCollateral(
      price: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateInterest(
      price: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claim(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    drachma(overrides?: CallOverrides): Promise<BigNumber>;

    echidnaBalanceExceedsLendersInterest(overrides?: CallOverrides): Promise<BigNumber>;

    echidnaBorrowerClaimedClosesTheLoan(overrides?: CallOverrides): Promise<BigNumber>;

    echidnaCollateralIsGreaterThanInterest(overrides?: CallOverrides): Promise<BigNumber>;

    echidnaDrachmaIsConstant(overrides?: CallOverrides): Promise<BigNumber>;

    echidnaDurationIsNonNegative(overrides?: CallOverrides): Promise<BigNumber>;

    echidnaIfAgreedMustBeInvoledWithALoan(overrides?: CallOverrides): Promise<BigNumber>;

    echidnaLenderAndBorrowerCannotBeTheSame(overrides?: CallOverrides): Promise<BigNumber>;

    echidnaListingDurationIsNonNegative(overrides?: CallOverrides): Promise<BigNumber>;

    echidnaListingPriceIsNonNegative(overrides?: CallOverrides): Promise<BigNumber>;

    echidnaOlympusIsConstant(overrides?: CallOverrides): Promise<BigNumber>;

    echidnaPriceIsNonNegative(overrides?: CallOverrides): Promise<BigNumber>;

    echidnaStartTimeIsNonNegative(overrides?: CallOverrides): Promise<BigNumber>;

    emergencyWithdraw(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    liquidate(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    listings(arg0: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    loans(arg0: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    olympus(overrides?: CallOverrides): Promise<BigNumber>;

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pause(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    payoff(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeListing(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    topup(
      tokenId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unpause(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<BigNumber>;

    updatePrices(
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _prices: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addListing(
      tokenId: PromiseOrValue<BigNumberish>,
      price: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    agreed(arg0: PromiseOrValue<string>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    borrow(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    calculateCollateral(
      price: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculateInterest(
      price: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claim(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    drachma(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    echidnaBalanceExceedsLendersInterest(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    echidnaBorrowerClaimedClosesTheLoan(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    echidnaCollateralIsGreaterThanInterest(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    echidnaDrachmaIsConstant(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    echidnaDurationIsNonNegative(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    echidnaIfAgreedMustBeInvoledWithALoan(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    echidnaLenderAndBorrowerCannotBeTheSame(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    echidnaListingDurationIsNonNegative(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    echidnaListingPriceIsNonNegative(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    echidnaOlympusIsConstant(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    echidnaPriceIsNonNegative(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    echidnaStartTimeIsNonNegative(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    emergencyWithdraw(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    liquidate(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    listings(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    loans(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    olympus(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pause(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    payoff(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeListing(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    topup(
      tokenId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updatePrices(
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _prices: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
