name: Frontend CI

on:
  push:
    branches-ignore: []

jobs:
  quality:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn && cd frontend/ && yarn
      - name: Build
        run: cd frontend/ && yarn build
